services:
  httpd:
    image: httpd:2.4.54-alpine
    container_name: httpd
    ports:
      - 80:80
    volumes:
      - ${DOCROOT}:/usr/local/apache2/htdocs/
      # - ${CONF}:/usr/local/apache2/conf/httpd.conf:ro
