#!/bin/bash
# run the httpd container to serve up docs

# Check to see if docker is running...
docker ps > /dev/null; if (( $? > 0 )); then echo "ERROR: docker daemon not running - please launch daemon and try again!"; exit 1; fi

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}"

if [[ $@ == **--restart** ]]; then
    docker-compose down
fi

export DOCROOT="../docs"
docker-compose up --force-recreate
